### ISSUE TITLE
Adicionar um link para este repo

### ISSUE THREAD

**Issue by pxpm** [pricescrawler/web-app#117]
Boas @scafer 

Estava a procurar no site e não encontrei nenhuma ligação para este repositório apesar de na página "About" fazer referência a ser open-source: 
![image](https://github.com/pricescrawler/web-app/assets/7188159/5d244607-07b7-41d6-ab56-d6dff381295e)

Um `... bla bla bla ... <a target="_blank" rel="nofollow" href="https://github.com/pricescrawler/web-app/"> open source</a>` pode ajudar a dar alguma visibilidade ao projeto. 

Ou um link no footer. 

Ou nada se não queres que o repositório seja facilmente descoberto. 🤷 

Bom projeto, se vir que tenho oportunidade de contribuir alguma coisa, vou estando atento. 🙏

**Comment by scafer** [comment]
Olá @pxpm,

Muito obrigado pelo teu apoio!
Se precisares de alguma coisa, é só dizer.

Ainda não adicionei por esse mesmo motivo, mas vou reavaliar essa questão.
Sente-te à vontade para me enviar uma mensagem pelo Discord.

Abraço!
